[package]
name = "slog"
version = "1.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, composable logging for Rust"
keywords = ["log", "logging", "structured", "hierarchical"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/slog-rs/"
homepage = "https://github.com/dpc/slog-rs"
repository = "https://github.com/dpc/slog-rs"
readme = "README.md"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[features]

std = []
default = ["std"]

max_level_off   = []
max_level_error = []
max_level_warn  = []
max_level_info  = []
max_level_debug = []
max_level_trace = []

release_max_level_off   = []
release_max_level_error = []
release_max_level_warn  = []
release_max_level_info  = []
release_max_level_debug = []
release_max_level_trace = []

[workspace]
members = ["crates/json", "crates/term", "crates/stdlog", "crates/syslog",
	"crates/bunyan", "crates/atomic", "crates/stream",
	"crates/example-lib", "crates/nursery", "crates/scope"]

[dev-dependencies]
slog-json = { path = "crates/json", version = "1" }
slog-term = { path = "crates/term", version = "1" }
slog-scope = { path = "crates/scope", version = "0" }
slog-stdlog = { path = "crates/stdlog", version = "1" }
slog-syslog = { path = "crates/syslog", version = "1.0.0-alpha8" }
slog-bunyan = { path = "crates/bunyan", version = "1" }
slog-atomic = { path = "crates/atomic", version = "0.4" }
slog-stream = { path = "crates/stream", version = "1" }
log = "0.3.6"
nix = "0.6.0"
lazy_static = "0.1.16"
